#!/bin/bash

# Numbers-> Number
# Compute the average of a set of numbers.
# Given 1 2         Expect 1.5
# Given 1.4 1.6,    Expect 1.5
# Given 1.2 1.5 1.8 Expect 1.5

if [ $# -eq 0 ]
then
  echo "Usage:"
  echo "  > average 1 2"
  echo "  1.50"
  echo "  > average 1.4 1.5 1.6"
  echo "  1.50"
  exit 1
else
  NUMBER_OF_ITEMS=$#
  SUM=0
  for i in $@
  do
    SUM=`echo "$SUM $i + p" | dc`
  done
  SCALE=2
  AVERAGE=`echo "$SUM / $NUMBER_OF_ITEMS"`
  echo "scale=$SCALE; $AVERAGE" | bc
  exit 0
fi

# Author Kevin Jackson
# Version completed 5/3/17
# TODO Handle non alphabetic input
# TODO Create an option for setting the scale.
